name: "Test Merge Requests"

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      -
        name: Build image locally
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            VCS_REF=${{ github.sha }}
            VCS_VER=${{ github.ref }}
          context: .
          file: ./Dockerfile
          load: true
          platforms: linux/amd64
          tags: docker.io/mailserver/testing:ci
      -
        name: Run all tests
        run: >
          NAME=docker.io/mailserver/testing:ci
          bash -c 'make generate-accounts tests'
        env:
          CI: true
